spring.application.name=SmartNotify
spring.datasource.url=jdbc:postgresql://localhost:5432/smartnotify
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madhumaneeshshetty5@gmail.com
spring.mail.password=ocloppncxszclsyl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true